### ISSUE TITLE
能不能兼容 “廿”、“卅”？

### ISSUE THREAD

**Issue by qlih** [nrchan/chinese-number-converter#3]
很棒的函数！在Sublime Text 4 中作为插件也运行很好（直接copy到Package/User目录下），和 Reg Replace 插件的plugin也协调工作很好。
全角中文的 “０-９”能识别转换吗？
在转换某些网文的章节编号时，发现有些用“廿niàn”、“卅sà”代替了20、30，如果能兼容就更方便了。谢谢！
㊟ 至于40卌xì、50圩、60圆、70进、80枯，等很少见。

**Comment by nrchan** [comment]
加了維基百科上提到的所有組合數字 :) 現在應該可以了
