### ISSUE TITLE
Bug Report: pypi 的新版库是空的

### ISSUE THREAD

**Issue by qlih** [nrchan/chinese-number-converter#5]
pip install --upgrade ChineseNumberUtils 安装1.1.1后没有文件。安装环境 MacOS 11.7 python3.10。（删除后重新安装也一样）
finder capture:

<img width="414" alt="截屏2023-04-20 17 36 40" src="https://user-images.githubusercontent.com/24715118/233325485-5568b383-6071-4fc1-8139-66f115ad7e0d.png">

PS version 1.0.3
print(convert.chinese2number("两百八十")) # 简体中文“两”

输出是180，我看了源码，觉得这种错误真的很隐蔽啊（输出了结果，还是整数，骗过了数据类型检查器——就是6万7那个）。

另外新版本功能挺好的，MIT许可也很NICE！🙏

**Comment by nrchan** [comment]
1.1.2 應該就沒問題了
