### ISSUE TITLE
建议：chinese2number 的输入检查

### ISSUE THREAD

**Issue by qlih** [nrchan/chinese-number-converter#6]
我用chinese2number的输入主要来自正则表达式的搜索结果，偶尔会有一些不太规范的情况，比如“百八十”人、十之“八九”、“三五十”个，不管“三七二十一”，这些都是日常说法，偶尔会出现在需要转换的数字序列中，此时，双引号中的数字并不符合转数字功能的语言表达习惯，这种情况是不是可以抛出个异常？当然不转换是我需要的。谢谢！！

**Comment by nrchan** [comment]
唉，因為是rule base的，這個不太可能。
如果用regex，限制一到九之間不連續或許可以刪掉一點 -> 例如：r"[一二三四五六七八九][一二三四五六七八九十]?" 就不會抓到十之八九的「八九」。但如你所能預見的，即便這樣也是會抓到「八」和「九」，而且這麼一來更難斷定這個「八」和「九」到底是不是慣用語了。
我想到兩個方法，一個就是建立常用詞表，另一個（雖然比較麻煩而且效果難以預期，但）你可以找找現成的中文NER模型，像這個：https://github.com/ckiplab/ckip-transformers。
還是謝謝你的建議。

**Comment by qlih** [comment]
了解，非常感谢。
